### ISSUE TITLE
ScanbotSDKOCRData.bundle isn't getting recognized

### ISSUE THREAD

**Issue by chris-paterson** [doo/scanbot-sdk-example-ios#11]
Hey!

I have added the SDK using `pod 'ScanbotSDK', :subspecs => ['OCR']`, and I see `ScanbotSDKOCRData.bundle` under resources. I also see it getting copied from the pods directory to the main project directory as part of the build phases:
- input: `${PODS_ROOT}/ScanbotSDK/AdditionalData/ScanbotSDKOCRData.bundle`
- output: `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/ScanbotSDKOCRData.bundle`

However, when I try to render a document using OCR, I get the following error: `Error Domain=ScanbotSDKErrorDomain Code=9 "(null)" UserInfo={ScanbotSDKErrorReason={ScanbotSDKErrorDomain}: Language data for text recognition is missing.}`. Similarly, `SBSDKOpticalTextRecognizer.installedLanguages()` gives 0 elements.

I have tried cleaning and fresh installing but I'm still running into the same issue.

Thanks!
Chris

**Comment by eddyfrank** [comment]
@chris-paterson Thanks for your report and providing the details.
We have just published a bugfix release **v1.9.1** for that.
