### ISSUE TITLE
module 'ScanbotSDK' not found

### ISSUE THREAD

**Issue by Daniyal073** [doo/scanbot-sdk-example-ios#9]

**Comment by eddyfrank** [comment]
Thanks for this report.

Seems like you didn't download and add the Scanbot SDK as mentioned in the [README](https://github.com/doo/scanbot-sdk-example-ios#how-to-run-this-example-app).

Please download and unzip the latest version of the Scanbot SDK for iOS:
https://download.scanbot.io/sdk/ios/scanbot-ios-sdk1.9.0.zip
